// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

 

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
    const count = new Map();
    for(const char of t) {
        count.set(char, (count.get(char) || 0) + 1)
    }
    for(const char of s) {
        count.set(char, count.get(char) - 1);
        if(count.get(char) === 0) {
            count.delete(char);
        }
    }
    return Array.from(count.keys())[0];
};